/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_selfimpr_android_HelloJNI */

#ifndef _Included_com_selfimpr_android_HelloJNI
#define _Included_com_selfimpr_android_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_selfimpr_android_HelloJNI
 * Method:    greet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_selfimpr_android_HelloJNI_greet
  (JNIEnv *, jclass);

/*
 * Class:     com_selfimpr_android_HelloJNI
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_selfimpr_android_HelloJNI_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
